# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMDemo02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMDemo02
	pod 'Moya'
	pod 'Alamofire'
    pod 'PKHUD'
  target 'MVVMDemo02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMDemo02UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
